const RELEASE_HOLD_UPDATE_HOLD_ID = 'RELEASE_HOLD_UPDATE_HOLD_ID';
const RELEASE_HOLD_UPDATE_STATUS = 'RELEASE_HOLD_UPDATE_STATUS';

export default {
  RELEASE_HOLD_UPDATE_HOLD_ID,
  RELEASE_HOLD_UPDATE_STATUS,
};
