const SET_ADDRESS = 'SET_ADDRESS';
const SET_BALANCE = 'SET_BALANCE';
const SET_BALANCE_ON_HOLD = 'SET_BALANCE_ON_HOLD';

export default {
  SET_ADDRESS,
  SET_BALANCE: SET_BALANCE,
  SET_BALANCE_ON_HOLD: SET_BALANCE_ON_HOLD,
}
