const SET_NOTARY = 'SET_NOTARY';
const UPDATE_SENDER = 'UPDATE_SENDER';
const UPDATE_RECEIVER = 'UPDATE_RECEIVER';
const UPDATE_SENDER_INPUT_IS_COMPLETED = 'UPDATE_SENDER_INPUT_IS_COMPLETED';
const UPDATE_RECEIVER_INPUT_IS_COMPLETED = 'UPDATE_RECEIVER_INPUT_IS_COMPLETED';

export default {
  SET_NOTARY,
  UPDATE_SENDER,
  UPDATE_SENDER_INPUT_IS_COMPLETED,
  UPDATE_RECEIVER,
  UPDATE_RECEIVER_INPUT_IS_COMPLETED,
};
