const APP_ADD_ACCOUNT = 'APP_ADD_ACCOUNT';
const APP_UPDATE_SELECTED_ACCOUNT_INDEX = 'APP_UPDATE_SELECTED_ACCOUNT_INDEX';
const APP_UPDATE_SELECTED_NAVIGATION_INDEX = 'APP_UPDATE_SELECTED_NAVIGATION_INDEX';

export default {
  APP_ADD_ACCOUNT,
  APP_UPDATE_SELECTED_ACCOUNT_INDEX,
  APP_UPDATE_SELECTED_NAVIGATION_INDEX,
};
