const TRANSACTION_STATUS_PENDING = 'pending';
const TRANSACTION_STATUS_SUCCESS = 'success';
const TRANSACTION_STATUS_ERROR = 'error';

const ROLE_USER = 'user';
const ROLE_NOTARY = 'notary';

export {
  ROLE_USER,
  ROLE_NOTARY,
  TRANSACTION_STATUS_PENDING,
  TRANSACTION_STATUS_SUCCESS,
  TRANSACTION_STATUS_ERROR,
}
