const EXECUTE_HOLD_UPDATE_AMOUNT = 'EXECUTE_HOLD_UPDATE_AMOUNT';
const EXECUTE_HOLD_UPDATE_HOLD_ID = 'EXECUTE_HOLD_UPDATE_HOLD_ID';
const EXECUTE_HOLD_UPDATE_STATUS = 'EXECUTE_HOLD_UPDATE_STATUS';

export default {
  EXECUTE_HOLD_UPDATE_AMOUNT,
  EXECUTE_HOLD_UPDATE_HOLD_ID,
  EXECUTE_HOLD_UPDATE_STATUS
};
