const TRANSFER_UPDATE_AMOUNT = 'TRANSFER_UPDATE_AMOUNT';
const TRANSFER_UPDATE_TO = 'TRANSFER_UPDATE_TO';
const TRANSFER_UPDATE_STATUS = 'TRANSFER_UPDATE_STATUS';

export default {
  TRANSFER_UPDATE_AMOUNT,
  TRANSFER_UPDATE_TO,
  TRANSFER_UPDATE_STATUS
};
