const CREATE_HOLD_UPDATE_HOLD_ID = 'CREATE_HOLD_UPDATE_HOLD_ID';
const CREATE_HOLD_UPDATE_AMOUNT = 'CREATE_HOLD_UPDATE_AMOUNT';
const CREATE_HOLD_UPDATE_TO = 'CREATE_HOLD_UPDATE_TO';
const CREATE_HOLD_UPDATE_EXPIRATION = 'CREATE_HOLD_UPDATE_EXPIRATION';
const CREATE_HOLD_UPDATE_NOTARY = 'CREATE_HOLD_UPDATE_NOTARY';
const CREATE_HOLD_UPDATE_STATUS = 'CREATE_HOLD_UPDATE_STATUS';

export default {
  CREATE_HOLD_UPDATE_HOLD_ID,
  CREATE_HOLD_UPDATE_AMOUNT,
  CREATE_HOLD_UPDATE_TO,
  CREATE_HOLD_UPDATE_EXPIRATION,
  CREATE_HOLD_UPDATE_NOTARY,
  CREATE_HOLD_UPDATE_STATUS,
};
